x-base: &base
  tty: true
  env_file: .env.local
  networks:
    botfi.localhost: {}
  volumes: &base_volumes
    - .devcontainer/.npmrc:/root/.npmrc:ro
    - .:/workspace
x-node: &node
  <<: *base
  build:
    context: .
    dockerfile: .devcontainer/Dockerfile.node22

services:
  platform:
    <<: *node
    container_name: repo-template.botfi.localhost
    hostname: repo-template.botfi.localhost
    working_dir: /workspace/platform
    env_file: platform/.env.local
    volumes:
      - platform-vscode-server:/root/.vscode-server
      - platform-pnpm:/pnpm
      - .devcontainer/.npmrc:/root/.npmrc:ro
      - .:/workspace
    ports:
      - 15000:15000 # main-app
volumes:
  platform-vscode-server: {}
  platform-pnpm: {}
